nodeLinker: node-modules

compressionLevel: mixed

enableGlobalCache: false

supportedArchitectures:
  os:
    - current
    - linux
    - darwin
  cpu:
    - x64
    - arm64

packageExtensions:
  "react-spinners@*":
    peerDependencies:
      react: "^18.0.0"
      react-dom: "^18.0.0"
